-- Create database table (private user data)
CREATE TABLE IF NOT EXISTS public.database (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    score BIGINT DEFAULT 0,
    coins BIGINT DEFAULT 0,
    level INTEGER DEFAULT 1,
    xp BIGINT DEFAULT 0,
    trees TEXT DEFAULT '[]',
    gadgets TEXT DEFAULT '[]',
    banned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create leaderboard table (public display data)
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id TEXT PRIMARY KEY REFERENCES public.database(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    score BIGINT DEFAULT 0,
    level INTEGER DEFAULT 1,
    coins BIGINT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.database ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access to the leaderboard
CREATE POLICY "Allow public read access to leaderboard" ON public.leaderboard
    FOR SELECT USING (TRUE);

-- IMPORTANT: No public INSERT, UPDATE, or DELETE policies for database or leaderboard. 
-- All modifications must go through the server using the Service Role Key.

-- Function to sync data from database to leaderboard
CREATE OR REPLACE FUNCTION public.sync_to_leaderboard()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.leaderboard (id, name, score, level, coins, updated_at)
    VALUES (NEW.id, NEW.name, NEW.score, NEW.level, NEW.coins, NEW.updated_at)
    ON CONFLICT (id) DO UPDATE
    SET name = EXCLUDED.name,
        score = EXCLUDED.score,
        level = EXCLUDED.level,
        coins = EXCLUDED.coins,
        updated_at = EXCLUDED.updated_at;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the sync function on INSERT or UPDATE of the database table
CREATE TRIGGER trigger_sync_to_leaderboard
AFTER INSERT OR UPDATE ON public.database
FOR EACH ROW
EXECUTE FUNCTION public.sync_to_leaderboard();

-- Create logs table
CREATE TABLE IF NOT EXISTS public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    action TEXT NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for logs
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

-- Enable Realtime for logs and leaderboard (Safe way)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.logs;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'leaderboard'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.leaderboard;
    END IF;
END $$;
