-- Create leaderboard table
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    score BIGINT DEFAULT 0,
    coins BIGINT DEFAULT 0,
    level INTEGER DEFAULT 1,
    xp BIGINT DEFAULT 0,
    trees TEXT DEFAULT '[]',
    gadgets TEXT DEFAULT '[]',
    banned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for leaderboard
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access to non-banned users (only specific fields should be public, but RLS is table-level)
-- We rely on the server to filter sensitive fields, but as a backup, we only allow reading non-banned users.
CREATE POLICY "Allow public read access to non-banned users" ON public.leaderboard
    FOR SELECT USING (banned = FALSE);

-- IMPORTANT: No public INSERT, UPDATE, or DELETE policies. 
-- All modifications must go through the server using the Service Role Key.

-- Create logs table
CREATE TABLE IF NOT EXISTS public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    action TEXT NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for logs
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

-- No public access to logs. Only the server (Service Role) can read/write logs.
-- This prevents users from spoofing logs or reading other users' transaction history.

-- Enable Realtime for logs
ALTER PUBLICATION supabase_realtime ADD TABLE public.logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.leaderboard;
