-- Create leaderboard table
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    score BIGINT DEFAULT 0,
    coins BIGINT DEFAULT 0,
    level INTEGER DEFAULT 1,
    xp BIGINT DEFAULT 0,
    trees TEXT DEFAULT '[]',
    gadgets TEXT DEFAULT '[]',
    banned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for leaderboard
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access to non-banned users
CREATE POLICY "Allow public read access to non-banned users" ON public.leaderboard
    FOR SELECT USING (banned = FALSE);

-- Create policy to allow users to update their own data
CREATE POLICY "Allow users to update their own data" ON public.leaderboard
    FOR ALL USING (true); -- Simplified for now as we use service role on server

-- Create logs table
CREATE TABLE IF NOT EXISTS public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    action TEXT NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for logs
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to insert their own logs
CREATE POLICY "Allow users to insert their own logs" ON public.logs
    FOR INSERT WITH CHECK (true);

-- Create policy to allow users to read their own logs
CREATE POLICY "Allow users to read their own logs" ON public.logs
    FOR SELECT USING (true);

-- Enable Realtime for logs
ALTER PUBLICATION supabase_realtime ADD TABLE public.logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.leaderboard;
